### ISSUE TITLE
Xcode Command Line Tools are required

### ISSUE THREAD

**Issue by andrii-rubtsov** [toebeann/gib#5]
Following instructions leads to the script hanging at `pnpm` part. (`-s` option hides the problem).
Installing `pnpm` manually and removing `-s` and  leads to the following:
```
pnpm --package=tsx --package=toebeann/gib\#semver:0.1.4 dlx gib
/Users/arubtsov/Library/Caches/pnpm/dlx/qha3igq3mu7kl7i477o2heyagm/18f8c119129-d85b:
 ERROR  Command failed with exit code 1: git ls-remote --refs https://github.com/toebeann/gib.git
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

This error happened while installing a direct dependency of /Users/arubtsov/Library/Caches/pnpm/dlx/qha3igq3mu7kl7i477o2heyagm/18f8c119129-d85b

pnpm: Command failed with exit code 1: git ls-remote --refs https://github.com/toebeann/gib.git
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    at makeError (/Users/arubtsov/.cache/node/corepack/v1/pnpm/9.1.1/dist/pnpm.cjs:19342:17)
    at handlePromise (/Users/arubtsov/.cache/node/corepack/v1/pnpm/9.1.1/dist/pnpm.cjs:19913:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRepoRefs (/Users/arubtsov/.cache/node/corepack/v1/pnpm/9.1.1/dist/pnpm.cjs:112239:23)
    at async resolveRef (/Users/arubtsov/.cache/node/corepack/v1/pnpm/9.1.1/dist/pnpm.cjs:112251:20)
    at async resolveGit (/Users/arubtsov/.cache/node/corepack/v1/pnpm/9.1.1/dist/pnpm.cjs:112190:24)
    at async Object.resolve (/Users/arubtsov/.cache/node/corepack/v1/pnpm/9.1.1/dist/pnpm.cjs:112501:173)
    at async run (/Users/arubtsov/.cache/node/corepack/v1/pnpm/9.1.1/dist/pnpm.cjs:130658:23)
Progress: resolved 1, reused 1, downloaded 0, added 0
```

https://forums.developer.apple.com/forums/thread/711512

In other words, the one needs to make sure that XCode Command Line tools are installed:
```
xcode-select --install
```

Then it works like a charm. You may want to update the README or even the script itself to automate. Thanks!

Hardware: Apple M1 Pro
MacOS version: 14.4.1

**Comment by toebeann** [comment]
Indeed, I hide a lot of things in the output by default because otherwise it prints a lot of intimidating things for average Mac users 😂

Thanks for letting me know, usually in my experience it will prompt the user to install the required xcode tools, I suppose in your case you may have rejected this previously and it is not prompting you again?

Anyway yeah I'll look at updating the script to include this so it doesn't matter, thanks for this

**Comment by andrii-rubtsov** [comment]
To be honest, I do not remember if I rejected the prompt in the past or not.

Thank you again for this great tool!

**Comment by toebeann** [comment]
Thanks again for the suggestion @andrii-rubtsov, I've pushed out v0.2.0 which contains a fix for this one 🥳
